# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

image: $CI_REGISTRY/anssi-fr/collab/rust-guide/worker:1.0.0

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    # - cargo install mdbook --git https://github.com/hg-anssi/mdBook.git --rev c5a35b9296c6d5e48570e30022bd69403050a9f4 --locked
    # - cargo install --path ./mdbook-checklist --locked
    # - cargo install --path ./mdbook-code-align --locked
    # - cargo install --path ./mdbook-extensions --locked
    - ./lang.sh en && mdbook build
    - ./lang.sh fr && mdbook build
    - mv book/fr/html book/en/html/fr
  artifacts:
    paths:
      - book/en/html

deploy-pages:
  stage: deploy
  script:
    - mv book/en/html/ public/
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
    path_prefix: $CI_COMMIT_REF_SLUG

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - cd examples
    - cargo build --verbose --features OK
    - cargo build --verbose --features KO
    - cargo test --verbose
